language: node_js
node_js:
- node
- 8
after_success:
- npm run coverage
- npm run build
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key:
    secure: dm4rNozfvXAWpDmVp+a+hMX2Qbwmxw/r5h5QntSdBZ6RldraxAcOVBvl0OQBmtQxdxOowTUrGKg2INZLV8o8UE9ax/i79DQljuVLjN0/PXOHACVwk7vR0VMvk4+UjGRr3UmhBW/iwK3+Wj7wzy55pw/V+kYfhsO0XMY5p75877dl5O8uuYbbrZWmnf8EOqFrZsSr2+EDAioquXqXZsYxR3p7NfYyQuKC8rGHKnQ80YwltnhSgS50atOC1gIcAEcXudpo33VtVVs6PobREsptSLCiytBEKlRv7fySeaNnDujhLkg7wNQ2ombqm8z3YxWSzjDoWHMkedMED4GCec4aYCvkOW/Jf67kNOxkwrJEUxXCviCmWYua8hvzZ/3dAe++TcAjzIZwP0lCZCjk8tVv4KLj2Rx6Mj9z+fSXXYd42Cq0Ti3C0b+9TuSXTQ3vG8ySmYlU1xCK1L8cEwd+6T3cGvGtNB8madS/SN0oc2zoJKfPAPhuuEWOkNOru+TSkhQy032hmoaenAudXyBKerU2n/NZFQKyOYzwu9Y4+3djzrJijyq7K59G08EPwFzvFZottctkCUSGn+p3D5ieLvhEnX/rv6N+WNRgl3oWIrSgW90iZUZw/rOtrkwl09/tFj9nGTWh7U/FrV1fDaBUsJfcLvEptr1BGv1dcMURWTU+IAQ=
  skip_cleanup: true
  on:
    repo: up9cloud/graphql-tools-type-int64
    branch: master
